server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/addressbook
    username: root
    password: abc123
    
    #mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl